env:
  global:
  - ENCRYPTION_LABEL: 5ebd09854806
language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_f71798f093d1_key -iv $encrypted_f71798f093d1_iv
  -in travis_deploy_rsa.pub.enc -out deploy_key -d
after_success:
  - bash scripts/deploy.sh
